root: true

parserOptions:
  ecmaVersion: 10
  sourceType: module
  ecmaFeatures:
    jsx: true

env:
  es6: true
  node: true

plugins:
  - import
  - prettier

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:import/errors
  - prettier

rules:
  eqeqeq: 0
  no-eq-null: 0
  no-negated-condition: 0
  no-unused-vars:
    - error
    - args: after-used
      argsIgnorePattern: '^_'
  no-var: error
  import/no-extraneous-dependencies: error
  prettier/prettier: error
  no-console: 0
  react/prop-types: off
  react/display-name: off
  react/no-children-prop: off
  react/react-in-jsx-scope: off

settings:
  react:
    version: 16.10.0

overrides:
  - files: '*.mdx'
    extends:
      - plugin:mdx/recommended
    rules:
      import/no-extraneous-dependencies: 0

  - files:
      - '**/test/**/*.js'
      - '**/*.test.js'
    env:
      jest: true
